### PR TITLE
Update binary version

### PR DESCRIPTION
**Pull request by FlorentPoinsaut**

### CODE REVIEW

**Comment by nikhuber** [comment]
Thank you for this pull request. I have made some adjustments to the Dockerfile and the build process. It's easier now to create a new Image with updated binaries. You can find the images on Dockerhub: https://hub.docker.com/r/nikhuber/sonar-scanner/

I'm closing this pull request because I believe it's not needed anymore.

**Comment by FlorentPoinsaut** [comment]
Wonderful!
Thank you :-)

**Comment by FlorentPoinsaut** [comment]
Hello,
I notice that the last build was canceled : https://hub.docker.com/r/nikhuber/sonar-scanner/builds
Could you please relaunch it?
Thank you in advance.
Regards,

**Comment by nikhuber** [comment]
The builds you see there are outdated. Now I use Travis to build and publish the image. Current image versions are up to date: https://hub.docker.com/r/nikhuber/sonar-scanner/tags

**Comment by FlorentPoinsaut** [comment]
All right!
Thank you :)

**Pull request closed without merging**
